app = "trader-hs"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  TRADER_BOT_SYMBOLS = "AAVEUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BTCUSDT,DOGEUSDT,DOTUSDT,ETHUSDT,FILUSDT"
  TRADER_BOT_TOP_COMBO_BOTS = "10"
  TRADER_BOT_TOP_COMBO_BOTS_STARTUP = "0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "4096mb"
